# Generated by Django 5.0.6 on 2024-06-08 17:05

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "to do": "an issue for which work has not yet begun",
        "in progress": "an issue actively being worked on",
        "done": "an issue for which work has been completed"
    }
    Status = apps.get_model("issue", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
