# Generated by Django 5.0.6 on 2024-06-08 17:05

from django.db import migrations

def populate_team(apps, schemaeditor):
    entries = {
        "Alpha": "team 1",
        "Bravo": "team 2",
        "Charlie": "team 3d"
    }
    Team = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()

def populate_role(apps, schemaeditor):
    entries = {
        "developer": "members who execute work defined in issues",
        "product owner": "person who defines what is built",
        "scrum master": "team's coach"
    }
    Role = apps.get_model("accounts","Role")
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_team),
        migrations.RunPython(populate_role),
    ]
