# Generated by Django 5.0.6 on 2024-06-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('accounts', '0002_auto_20240608_0408'),
    ]

    operations = [
    ]
